### ISSUE TITLE
Unsafe kludge parsing TZUTC

### ISSUE THREAD

**Issue by vit1251** [vit1251/golden#41]
```
2020/05/06 01:48:47 http: panic serving 127.0.0.1:34814: runtime error: index out of range [0] with length 0
goroutine 7442 [running]:
net/http.(*conn).serve.func1(0x9c7c840)
        /usr/lib/golang/src/net/http/server.go:1767 +0xed
panic(0x8541740, 0x9da35e0)
        /usr/lib/golang/src/runtime/panic.go:679 +0x16b
github.com/vit1251/golden/pkg/fidotime.(*TimeZoneParser).Parse(0x9ca56f0, 0x0, 0x0, 0x2, 0x0, 0x0)
        /home/user/src/golden/pkg/fidotime/TimeZoneParser.go:20 +0x340
github.com/vit1251/golden/pkg/tosser.(*Tosser).processNewEchoMessage(0x9d5c6a0, 0x9c529c0, 0x9d5cce0, 0x700, 0x9d5cce0)
        /home/user/src/golden/pkg/tosser/Tosser_Inbound.go:208 +0x455
github.com/vit1251/golden/pkg/tosser.(*Tosser).processNewMessage(0x9d5c6a0, 0x9c529c0, 0x9f70000, 0x573, 0x700, 0x0, 0x0)
        /home/user/src/golden/pkg/tosser/Tosser_Inbound.go:80 +0xca
github.com/vit1251/golden/pkg/tosser.(*Tosser).ProcessPacket(0x9d5c6a0, 0x9cd5080, 0x27, 0x0, 0x0)
        /home/user/src/golden/pkg/tosser/Tosser_Inbound.go:306 +0x10f
github.com/vit1251/golden/pkg/tosser.(*Tosser).processARCmail(0x9d5c6a0, 0x9d5d420, 0x9c47998, 0x1)
        /home/user/src/golden/pkg/tosser/Tosser_Inbound.go:368 +0x219
github.com/vit1251/golden/pkg/tosser.(*Tosser).ProcessInbound(0x9d5c6a0, 0x14, 0x0)
        /home/user/src/golden/pkg/tosser/Tosser_Inbound.go:469 +0x281
github.com/vit1251/golden/pkg/tosser.(*Tosser).Toss(0x9d5c6a0)
        /home/user/src/golden/pkg/tosser/Tosser.go:44 +0x63
github.com/vit1251/golden/pkg/tosser.(*TosserManager).Toss(0x9d81a90)
        /home/user/src/golden/pkg/tosser/TosserManager.go:415 +0x2f
github.com/vit1251/golden/pkg/ui/api.(*APIServiceManageCompleteAction).ServeHTTP.func1(0x9d81a90)
        /home/user/src/golden/pkg/ui/api/APIServiceManageCompleteAction.go:99 +0x21
reflect.Value.call(0x84dc880, 0x858f2a0, 0x13, 0x856bd50, 0x4, 0x9c0e2a0, 0x1, 0x1, 0x1, 0x0, ...)
        /usr/lib/golang/src/reflect/value.go:460 +0x557
reflect.Value.Call(0x84dc880, 0x858f2a0, 0x13, 0x9c0e2a0, 0x1, 0x1, 0x9cce1e0, 0x9c0e2a0, 0x1)
        /usr/lib/golang/src/reflect/value.go:321 +0x7a
go.uber.org/dig.(*Container).Invoke(0x9cce1e0, 0x84dc880, 0x858f2a0, 0x0, 0x0, 0x0, 0x4, 0x0)
        /home/user/go/pkg/mod/go.uber.org/dig@v1.9.0/dig.go:397 +0x2a6
github.com/vit1251/golden/pkg/ui/api.(*APIServiceManageCompleteAction).ServeHTTP(0x9d02008, 0x86179a0, 0x9c76120, 0x9c9c900)
        /home/user/src/golden/pkg/ui/api/APIServiceManageCompleteAction.go:98 +0x368
net/http.HandlerFunc.ServeHTTP(0x9c0f100, 0x86179a0, 0x9c76120, 0x9c9c900)
        /usr/lib/golang/src/net/http/server.go:2007 +0x34
github.com/gorilla/mux.(*Router).ServeHTTP(0x9c7c7e0, 0x86179a0, 0x9c76120, 0x9c9c380)
        /home/user/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xbb
net/http.serverHandler.ServeHTTP(0x9c76bd0, 0x86179a0, 0x9c76120, 0x9c9c380)
        /usr/lib/golang/src/net/http/server.go:2802 +0x84
net/http.(*conn).serve(0x9c7c840, 0x8618360, 0x9d5c260)
        /usr/lib/golang/src/net/http/server.go:1890 +0x7ad
created by net/http.(*Server).Serve
        /usr/lib/golang/src/net/http/server.go:2928 +0x30d
```

**Comment by vit1251** [comment]
```
panic: runtime error: index out of range [0] with length 0
goroutine 30 [running]:
github.com/vit1251/golden/pkg/fidotime.(*TimeZoneParser).Parse(0xa041c8c, 0x0, 0x0, 0x2, 0x0, 0x0)
        /home/user/src/golden/pkg/fidotime/TimeZoneParser.go:20 +0x340
github.com/vit1251/golden/pkg/tosser.(*Tosser).processNewEchoMessage(0xa10f6e0, 0xa10c9c0, 0xa0e6840, 0x700, 0xa0e6840)
        /home/user/src/golden/pkg/tosser/Tosser_Inbound.go:208 +0x455
github.com/vit1251/golden/pkg/tosser.(*Tosser).processNewMessage(0xa10f6e0, 0xa10c9c0, 0xa090300, 0x573, 0x700, 0x0, 0x0)
        /home/user/src/golden/pkg/tosser/Tosser_Inbound.go:80 +0xca
github.com/vit1251/golden/pkg/tosser.(*Tosser).ProcessPacket(0xa10f6e0, 0xa0228a0, 0x27, 0x0, 0x0)
        /home/user/src/golden/pkg/tosser/Tosser_Inbound.go:306 +0x10f
github.com/vit1251/golden/pkg/tosser.(*Tosser).processARCmail(0xa10f6e0, 0xa344c20, 0xa047f34, 0x1)
        /home/user/src/golden/pkg/tosser/Tosser_Inbound.go:368 +0x219
github.com/vit1251/golden/pkg/tosser.(*Tosser).ProcessInbound(0xa10f6e0, 0x14, 0x0)
        /home/user/src/golden/pkg/tosser/Tosser_Inbound.go:471 +0x281
github.com/vit1251/golden/pkg/tosser.(*Tosser).Toss(0xa10f6e0)
        /home/user/src/golden/pkg/tosser/Tosser.go:44 +0x63
github.com/vit1251/golden/pkg/tosser.(*TosserManager).processTosser(0xa0e61e0)
        /home/user/src/golden/pkg/tosser/TosserManager.go:72 +0x2f
github.com/vit1251/golden/pkg/tosser.(*TosserManager).run(0xa0e61e0)
        /home/user/src/golden/pkg/tosser/TosserManager.go:85 +0x14b
created by github.com/vit1251/golden/pkg/tosser.NewTosserManager
        /home/user/src/golden/pkg/tosser/TosserManager.go:61 +0xe9
В логе я обнаружил вот такую строку:
2020/10/19 02:40:54 Meet kludge: name = [84 90 85 84 67] value = [32]
```
